//DESTINATION ENDPOINTS

GET http://localhost:3000/destinations HTTP/1.1

###

POST http://localhost:3000/destinations/new
Content-Type: application/json

{
"name": "Kulturhuset",
"district": "Stockholm City",
"latitude": "78954533",
"longitude": "2792782"
}

###

//TO GET A SINGLE DESTINATION, PUT AN ID AT THHE END OF URL
GET http://localhost:3000/destination/


###

// TO UPDATE A DESTINATION, OUT A ID AT THE END OF URL

PUT http://localhost:3000/destinations/update/
Content-Type: application/json

{
"name": "Lilla Bajskorvsparken",
"district": "Whereever",
"latitude": "12345678",
"longitude": "98765432"
}

###
//TO DELETE A DESTINATION, PUT AN ID AT THE END OF URL

DELETE  http://localhost:3000/destinations/delete/63946e637bcd94334cac4aba
###
