//DESTINATION ENDPOINTS

GET http://localhost:3000/destinations HTTP/1.1

###

POST http://localhost:3000/destinations/new
Content-Type: application/json

{
"name": "Skånelängtans Parklek",
"district": "Södermalm",
"latitude": "59.31136",
"longitude": "18.07048"
}

###

//TO GET A SINGLE DESTINATION, PUT AN ID AT THHE END OF URL
GET http://localhost:3000/destination/


###

// TO UPDATE A DESTINATION, PUT A ID AT THE END OF URL

PUT http://localhost:3000/destinations/update/
Content-Type: application/json

{
"name": "Lumaparken",
"district": "Hammarby Sjöstad",
"latitude": "59.31109",
"longitude": "18.02225"
}

###
//TO DELETE A DESTINATION, PUT AN ID AT THE END OF URL

DELETE  http://localhost:3000/destinations/delete/
###
